version: '3'

services:
  mongo:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo_config:/data/configdb
    ports:
      - 27017:27017

  web_worker:
    build: .
    command: invoke start-web-worker
    environment:
      - DOCKER_MONGO=mongo
    volumes:
      - ./invoke.yaml:/facerecognitionsystem/invoke.yaml
    ports:
      - 8000:8000
    depends_on:
      - mongo

